src/br/edu/ifsuldeminas/dwjloc/controller/AluguelController.java
package br.edu.ifsuldeminas.dwjloc.controller;

import br.edu.ifsuldeminas.dwjloc.dao.Dao;
import br.edu.ifsuldeminas.dwjloc.dao.DaoFerramenta;
import br.edu.ifsuldeminas.dwjloc.dao.DaoFerramentaAluguel;
import br.edu.ifsuldeminas.dwjloc.lib.LibConstantes;
import br.edu.ifsuldeminas.dwjloc.model.*;
import br.edu.ifsuldeminas.dwjloc.util.JPAUtil;
import com.mysql.jdbc.util.TimezoneDump;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import java.sql.Time;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.*;

@ManagedBean
@ViewScoped
public class AluguelController
{
    private Integer idCliente;
    private Integer idTipo;
    private Integer quantidade;

    private Calendar dataLocacao = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));
    private Calendar dataDevolucao = Calendar.getInstance();

    public void adicionarLocacao()
    {
        if(!validar())
        {
            return;
        }

        // Lista de ferramentas disponíveis
        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();

        try
        {
            Usuario usuario = new Dao<Usuario>(Usuario.class).getById(idCliente, manager);

            TipoFerramenta tipo = new Dao<TipoFerramenta>(TipoFerramenta.class).getById(idTipo, manager);
            EstadoFerramenta estadoDisponivel = new Dao<EstadoFerramenta>(EstadoFerramenta.class).getById(LibConstantes.Banco.ID_ESTADO_DISPONIVEL, manager);
            EstadoFerramenta estadoAlugado = new Dao<EstadoFerramenta>(EstadoFerramenta.class).getById(LibConstantes.Banco.ID_ESTADO_ALUGADO, manager);

            List<Ferramenta> disponiveis = new DaoFerramenta().getByTipoAndEstado(tipo, estadoDisponivel, manager);

            List<Ferramenta> ferramentas = disponiveis.subList(0, quantidade);

            for (Ferramenta ferramenta : ferramentas)
            {
                FerramentaAluguel locacao = new FerramentaAluguel();
                locacao.setPago(false);
                locacao.setEntregue(false);
                dataLocacao.set(Calendar.HOUR_OF_DAY, 0);
                dataDevolucao.set(Calendar.HOUR_OF_DAY, 0);
                locacao.setDataLocacao(dataLocacao);
                locacao.setPrazoDevolucao(dataDevolucao);
                locacao.setFerramenta(ferramenta);
                locacao.setUsuario(usuario);

                locacao.setAcrescimo(0.0f);
                locacao.setDesconto(0.0f);

                locacao.setMulta(false);

                ferramenta.setEstado(estadoAlugado);

                locacao.setValorDiario(locacao.getFerramenta().getPrecoAluguel());

                new Dao<FerramentaAluguel>(FerramentaAluguel.class).add(locacao, manager);
            }

            manager.getTransaction().commit();
        }catch (Exception e)
        {
            FacesContext.getCurrentInstance().addMessage("aluguel", new FacesMessage("Falha na locação."));
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public boolean validar()
    {
        boolean ok = true;

        if(idCliente == null || idCliente == 0)
        {
            FacesContext.getCurrentInstance().addMessage("aluguel", new FacesMessage("Cliente obrigatório."));

            ok = false;
        }
        if(idTipo == null || idTipo == 0)
        {
            FacesContext.getCurrentInstance().addMessage("aluguel", new FacesMessage("Tipo obrigatório."));

            ok = false;
        }
        if(quantidade == null || quantidade == 0)
        {
            FacesContext.getCurrentInstance().addMessage("aluguel", new FacesMessage("Quantidade obrigatória."));

            ok = false;
        }
        if(dataLocacao.compareTo(dataDevolucao) > 0)
        {
            FacesContext.getCurrentInstance().addMessage("aluguel", new FacesMessage("A data de locação deve ser anterior ou igual à data de devolução."));

            ok = false;
        }
        return ok;
    }

    public void remover(FerramentaAluguel locacao)
    {
        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();
        try
        {
            EstadoFerramenta estadoDisponivel = new Dao<EstadoFerramenta>(EstadoFerramenta.class).getById(LibConstantes.Banco.ID_ESTADO_DISPONIVEL, manager);

            locacao = new Dao<FerramentaAluguel>(FerramentaAluguel.class).getById(locacao.getId(), manager);
            locacao.getFerramenta().setEstado(estadoDisponivel);

            new Dao<FerramentaAluguel>(FerramentaAluguel.class).remove(locacao, manager);

            manager.getTransaction().commit();
        }catch (Exception e)
        {
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public void entregar(FerramentaAluguel locacao)
    {
        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();

        Calendar dataAtual = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));
        dataAtual.set(Calendar.HOUR_OF_DAY, 0);

        try
        {
            locacao = new Dao<FerramentaAluguel>(FerramentaAluguel.class).getById(locacao.getId(), manager);

            locacao.setDataDevolucao(dataAtual);
            locacao.setAcrescimo(getAcrescimo(locacao));
            locacao.setDesconto(getDesconto(locacao));
            locacao.setEntregue(true);

            locacao.setFerramenta(new Dao<Ferramenta>(Ferramenta.class).getById(locacao.getFerramenta().getId(), manager));

            EstadoFerramenta estado = new EstadoFerramenta();
            estado.setId(locacao.getMulta() ? LibConstantes.Banco.ID_ESTADO_DANIFICADO : LibConstantes.Banco.ID_ESTADO_DISPONIVEL);
            locacao.getFerramenta().setEstado(estado);

            manager.getTransaction().commit();
        }catch (Exception e)
        {
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public void pagar(FerramentaAluguel locacao)
    {
        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();

        try
        {
            locacao = new Dao<FerramentaAluguel>(FerramentaAluguel.class).getById(locacao.getId(), manager);
            locacao.setPago(true);

            manager.getTransaction().commit();
        }catch (Exception e)
        {
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public Float getAcrescimo(FerramentaAluguel locacao)
    {
        if(locacao.getEntregue())
        {
            return locacao.getAcrescimo();
        }

        Calendar dataFinal = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));

        Calendar dataInicial = locacao.getDataLocacao();
        Calendar prazoDevolucao = locacao.getPrazoDevolucao();

        dataInicial.set(Calendar.HOUR_OF_DAY, 0);
        dataFinal.set(Calendar.HOUR_OF_DAY, 0);
        prazoDevolucao.set(Calendar.HOUR_OF_DAY, 0);

        Float acrescimo = 0.0f;

        if(dataFinal.compareTo(prazoDevolucao) > 0)
        {
            long atraso = (dataFinal.getTimeInMillis() - prazoDevolucao.getTimeInMillis()) / (24 * 60 * 60 * 1000);
            acrescimo += atraso * locacao.getValorDiario() * (1 + LibConstantes.Financeiro.ACRESCIMO_ATRASO);
        }

        if(locacao.getMulta())
        {
            acrescimo += locacao.getFerramenta().getPreco();
        }

        return acrescimo;
    }

    public Float getDesconto(FerramentaAluguel locacao)
    {
        if(locacao.getEntregue())
        {
           return locacao.getDesconto();
        }

        Calendar dataFinal = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));

        Calendar dataInicial = locacao.getDataLocacao();
        Calendar prazoDevolucao = locacao.getPrazoDevolucao();

        dataInicial.set(Calendar.HOUR_OF_DAY, 0);
        dataFinal.set(Calendar.HOUR_OF_DAY, 0);
        prazoDevolucao.set(Calendar.HOUR_OF_DAY, 0);

        Float desconto = 0.0f;

        if(dataFinal.compareTo(prazoDevolucao) < 0)
        {
            long adiantamento = (prazoDevolucao.getTimeInMillis() - dataFinal.getTimeInMillis()) / (24 * 60 * 60 * 1000);
            desconto += adiantamento * locacao.getValorDiario();
        }

        return desconto;
    }

    public Float getValorTotal(FerramentaAluguel locacao)
    {
        Calendar dataFinal;
        if(locacao.getEntregue())
        {
            dataFinal = locacao.getDataDevolucao();
        }else
        {
            dataFinal = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));
        }

        Calendar dataInicial = locacao.getDataLocacao();
        Calendar prazoDevolucao = locacao.getPrazoDevolucao();

        dataInicial.set(Calendar.HOUR_OF_DAY, 0);
        dataFinal.set(Calendar.HOUR_OF_DAY, 0);
        prazoDevolucao.set(Calendar.HOUR_OF_DAY, 0);

        Float valorAluguel = 0.0f;

        long tempoLocacao = (prazoDevolucao.getTimeInMillis() - dataInicial.getTimeInMillis()) / (24 * 60 * 60 * 1000);
        tempoLocacao = Math.max(tempoLocacao, 1);

        valorAluguel += tempoLocacao * locacao.getValorDiario();

        valorAluguel += getAcrescimo(locacao);
        valorAluguel -= getDesconto(locacao);

        return valorAluguel;
    }

    public List<Integer> getQuantidadeDisponivel()
    {
        if(idTipo == null)
        {
            return new ArrayList<>();
        }

        TipoFerramenta tipo = new Dao<TipoFerramenta>(TipoFerramenta.class).getById(idTipo);

src/br/edu/ifsuldeminas/dwjloc/controller/EstadoFerramentaController.java
package br.edu.ifsuldeminas.dwjloc.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.edu.ifsuldeminas.dwjloc.dao.Dao;
import br.edu.ifsuldeminas.dwjloc.lib.LibConstantes;
import br.edu.ifsuldeminas.dwjloc.model.EstadoFerramenta;

@ManagedBean
@ViewScoped
public class EstadoFerramentaController
{
	private EstadoFerramenta estadoFerramenta = new EstadoFerramenta();

	public EstadoFerramenta getEstadoFerramenta() {
		return estadoFerramenta;
	}

	public void setEstadoFerramenta(EstadoFerramenta estadoFerramenta) {
		this.estadoFerramenta = estadoFerramenta;
	}
	
	public List<EstadoFerramenta> getEstadosFerramentas()
	{
		return new Dao<EstadoFerramenta>(EstadoFerramenta.class).getAll();
	}
	
	public void carregar(EstadoFerramenta estadoFerramenta)
	{
		if(isNotConstant(estadoFerramenta.getId()))
			this.estadoFerramenta = estadoFerramenta;
		else
			FacesContext.getCurrentInstance().addMessage("estadoferramenta", new FacesMessage("O estado " + estadoFerramenta.getNome() + " é constante e não pode ser alterado."));

	}
	
	public void gravar(EstadoFerramenta estadoFerramenta)
	{
		if(estadoFerramenta.getId() == null)
		{
			new Dao<EstadoFerramenta>(EstadoFerramenta.class).add(estadoFerramenta);			
		}else
		{
			new Dao<EstadoFerramenta>(EstadoFerramenta.class).update(estadoFerramenta);
		}
		this.estadoFerramenta = new EstadoFerramenta();
	}
	
	public void remover(EstadoFerramenta estadoFerramenta)
	{
		if(isNotConstant(estadoFerramenta.getId()))
			new Dao<EstadoFerramenta>(EstadoFerramenta.class).remove(estadoFerramenta);
		else
			FacesContext.getCurrentInstance().addMessage("estadoferramenta", new FacesMessage("O estado " + estadoFerramenta.getNome() + " é constante e não pode ser alterado."));

	}

	public boolean isNotConstant(Integer id)
	{
		return id != LibConstantes.Banco.ID_ESTADO_DISPONIVEL && id != LibConstantes.Banco.ID_ESTADO_ALUGADO && id != LibConstantes.Banco.ID_ESTADO_DANIFICADO;
	}

	public String buttonDisabled(Integer id)
	{
		return !isNotConstant(id) ? " disabled" : "";
	}
}

src/br/edu/ifsuldeminas/dwjloc/controller/GrupoController.java
package br.edu.ifsuldeminas.dwjloc.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.edu.ifsuldeminas.dwjloc.dao.Dao;
import br.edu.ifsuldeminas.dwjloc.lib.LibConstantes;
import br.edu.ifsuldeminas.dwjloc.model.Grupo;

@ManagedBean
@ViewScoped
public class GrupoController
{
	private Grupo grupo = new Grupo();

	public Grupo getGrupo() {
		return grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	public List<Grupo> getGrupos() {
		return new Dao<Grupo>(Grupo.class).getAll();
	}

	public void carregar(Grupo grupo) {
		if(isNotConstant(grupo.getId()))
		{
			this.grupo = grupo;
		}else
		{
			FacesContext.getCurrentInstance().addMessage("grupo", new FacesMessage("O grupo " + grupo.getNome() + " é constante e não pode ser alterado."));
		}
	}

	public void gravar(Grupo grupo) {
		if (grupo.getId() == null) {
			new Dao<Grupo>(Grupo.class).add(grupo);
		} else {
			new Dao<Grupo>(Grupo.class).update(grupo);
		}
		this.grupo = new Grupo();
	}

	public void remover(Grupo grupo) {
		if(isNotConstant(grupo.getId()))
		{
			new Dao<Grupo>(Grupo.class).remove(grupo);
		}else
		{
			FacesContext.getCurrentInstance().addMessage("grupo", new FacesMessage("O grupo " + grupo.getNome() + " é constante e não pode ser alterado."));
		}
	}
	
	public boolean isNotConstant(Integer id)
	{
		return id != LibConstantes.Banco.ID_GRUPO_CLIENTES && id != LibConstantes.Banco.ID_GRUPO_ADMINISTRADORES;
	}

	public boolean isAdministrador(Integer id)
	{
		return id == LibConstantes.Banco.ID_GRUPO_ADMINISTRADORES;
	}
	public String buttonDisabled(Integer id)
	{
		return !isNotConstant(id) ? " disabled" : "";
	}
}

src/br/edu/ifsuldeminas/dwjloc/controller/GrupoFuncionalidadesController.java
package br.edu.ifsuldeminas.dwjloc.controller;

import br.edu.ifsuldeminas.dwjloc.dao.Dao;
import br.edu.ifsuldeminas.dwjloc.lib.LibConstantes;
import br.edu.ifsuldeminas.dwjloc.model.Funcionalidade;
import br.edu.ifsuldeminas.dwjloc.model.Grupo;
import br.edu.ifsuldeminas.dwjloc.util.JPAUtil;
import br.edu.ifsuldeminas.dwjloc.dao.GrupoDao;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.persistence.EntityManager;
import java.util.ArrayList;
import java.util.List;

@ManagedBean
@ViewScoped
public class GrupoFuncionalidadesController
{
    private Integer idGrupo;
    private Integer idFuncionalidade;

    public List<Funcionalidade> getAllFuncionalidades()
    {
        return new Dao<Funcionalidade>(Funcionalidade.class).getAll();
    }

    public List<Funcionalidade> getGrupoFuncionalidades()
    {
        if(idGrupo == null || idGrupo == 0)
        {
            return new ArrayList<>();
        }

        Grupo grupo = new Dao<Grupo>(Grupo.class).getById(idGrupo);

        return grupo.getFuncionalidades();
    }

    public void adicionarFuncionalidade()
    {
        if(!validar())
        {
            return;
        }

        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();

        try
        {
            Grupo grupo = new Dao<Grupo>(Grupo.class).getById(idGrupo, manager);
            Funcionalidade funcionalidade = new Funcionalidade();
            funcionalidade.setId(idFuncionalidade);

            grupo.getFuncionalidades().add(funcionalidade);
            manager.getTransaction().commit();
        }catch (Exception e)
        {
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public void remover(Funcionalidade funcionalidade)
    {
        EntityManager manager = JPAUtil.getEntityManager();
        manager.getTransaction().begin();

        try
        {
            Grupo grupo = new Dao<Grupo>(Grupo.class).getById(idGrupo, manager);

            funcionalidade = new Dao<Funcionalidade>(Funcionalidade.class).getById(funcionalidade.getId(), manager);

            grupo.getFuncionalidades().remove(funcionalidade);
            manager.getTransaction().commit();
        }catch (Exception e)
        {
            manager.getTransaction().rollback();
        }finally
        {
            manager.close();
        }
    }

    public boolean validar()
    {
        boolean ok = true;

        if(idGrupo == null || idGrupo == 0)
        {
            FacesContext.getCurrentInstance().addMessage("grupofuncionalidades", new FacesMessage("Grupo obrigatório."));

            ok = false;
        }
        if(idFuncionalidade == null || idFuncionalidade == 0)
        {
            FacesContext.getCurrentInstance().addMessage("grupofuncionalidades", new FacesMessage("Funcionalidade obrigatório."));

            ok = false;
        }

        return ok;
    }

    public List<Funcionalidade> getMissingFuncionalidades(Integer idGrupo)
    {
        return new GrupoDao().getMissingFuncionalidades(idGrupo);
    }

    public Integer getIdGrupo()
    {
        return idGrupo;
    }

    public void setIdGrupo(Integer idGrupo)
    {
        this.idGrupo = idGrupo;
    }

    public Integer getIdFuncionalidade()
    {
        return idFuncionalidade;
    }

    public void setIdFuncionalidade(Integer idFuncionalidade)
    {
        this.idFuncionalidade = idFuncionalidade;
    }

    public String removeDisabled(Integer id)
    {
        return (id == LibConstantes.Banco.ID_GRUPO_CLIENTES || id == LibConstantes.Banco.ID_GRUPO_ADMINISTRADORES) ? " disabled" : "";

    }

}

web/estadoferramenta.xhtml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html 
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	>
	  
	<ui:composition template="_template.xhtml">
	
	<ui:define name="title">Estado da ferramenta</ui:define>
	<ui:define name="titulo">Estado da ferramenta</ui:define>
	  
	  <ui:define name="content">
	  <h:messages class="alert alert-danger"/>
	  <div class="panel panel-default">
		  <div class="panel-heading">
		    <h3 class="panel-title">Cadastrar</h3>
		  </div>
		  <div class="panel-body">
	  	<h:form>

	  			<div class="form-group">
	  				<label>Nome</label>
	  				<h:inputText id="nome" value="#{estadoFerramentaController.estadoFerramenta.nome}"  required="true" requiredMessage="Nome obrigatório." class="form-control"/>
	  			</div>
	  				
	  			<div class="form-group">
	  				<label>Descrição</label>
	  				<h:inputText id="desc" value="#{estadoFerramentaController.estadoFerramenta.descricao}" class="form-control"/>
	  			</div>
	  				
	  			<div align="right">
	  				<h:commandButton value="Gravar" action="#{estadoFerramentaController.gravar(estadoFerramentaController.estadoFerramenta)}" class="btn btn-success"/>
	  			</div>
	  				

	  	</h:form>
	  	</div>
	  	</div>
	  	
	  	<div class="panel panel-default">
  		<div class="panel-body">
	  	<h:form id="formTabelaEstados">
	  		<h:dataTable id="tabelaEstados" value="#{estadoFerramentaController.estadosFerramentas}" var="estado" class="table table-hover">
				<h:column>
					<f:facet name="header">Nome</f:facet>
					<h:outputText value="#{estado.nome}"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">Descrição</f:facet>
					<h:outputText value="#{estado.descricao}"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">Atualizar</f:facet>
					<h:commandLink value="Atualizar" disabled="#{!grupoController.isNotConstant(estado.id)}" action="#{estadoFerramentaController.carregar(estado)}" class="btn btn-warning#{estadoFerramentaController.buttonDisabled(estado.id)}"/>
				</h:column>
				
				<h:column>
					<f:facet name="header">Remover</f:facet>
					<h:commandLink value="Remover" disabled="#{!estadoFerramentaController.isNotConstant(estado.id)}" action="#{estadoFerramentaController.remover(estado)}" class="btn btn-danger#{estadoFerramentaController.buttonDisabled(estado.id)}"/>
				</h:column>
					  			
	  		</h:dataTable>
	  	</h:form>
	  	</div>
	  	</div>
	  	
	  	</ui:define>
	  </ui:composition>
</html>

web/grupofuncionalidades.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
>

<ui:composition template="_template.xhtml">

    <ui:define name="title">Funcionalidades por grupo</ui:define>
    <ui:define name="titulo">Funcionalidades por grupo</ui:define>

    <ui:define name="content">
    <h:messages class="alert alert-danger"/>
        <h:form class="form-inline">
            
          <div class="panel panel-success">
		  <div class="panel-heading">
		    <h3 class="panel-title">Grupo</h3>
		  </div>
		  <div class="panel-body">
		 	<div class="form-group">
                <h:selectOneMenu id="grupo" value="#{grupoFuncionalidadesController.idGrupo}" class="form-control">
                    <f:selectItem itemLabel="Selecione um grupo" noSelectionOption="true"/>
                    <f:selectItems
                            value="#{grupoController.grupos}"
                            var="grupo"
                            itemLabel="#{grupo.nome}"
                            itemValue="#{grupo.id}"
                    />
                    <f:ajax event="change" execute="btnRemove btnAdd funcionalidade tabelaFuncionalidades" render="btnRemove btnAdd funcionalidade tabelaFuncionalidades"/>
                </h:selectOneMenu>
              </div>
            </div>
            </div>
            
            
           <div class="panel panel-success">
		  <div class="panel-heading">
		    <h3 class="panel-title">Nova Funcionalidade</h3>
		  </div>
		  <div class="panel-body">
		  		<div class="form-group">
                    <h:selectOneMenu id="funcionalidade" value="#{grupoFuncionalidadesController.idFuncionalidade}" class="form-control">
                        <f:selectItem itemLabel="Selecione uma funcionalidade" noSelectionOption="true"/>
                        <f:selectItems
                                value="#{grupoFuncionalidadesController.getMissingFuncionalidades(grupoFuncionalidadesController.idGrupo)}"
                                var="funcionalidade"
                                itemLabel="#{funcionalidade.nome}"
                                itemValue="#{funcionalidade.id}"
                        />
                    </h:selectOneMenu>
                 </div>

                    <h:commandButton id="btnAdd" disabled="#{!grupoController.isNotConstant(grupoFuncionalidadesController.idGrupo)}" action="#{grupoFuncionalidadesController.adicionarFuncionalidade}" value="Adicionar" class="btn btn-success"/>
                </div>
                </div>

            <div class="panel panel-info">
		  <div class="panel-heading">
		    <h3 class="panel-title">Funcionalidades</h3>
		  </div>
		  <div class="panel-body">

                <h:dataTable id="tabelaFuncionalidades" value="#{grupoFuncionalidadesController.grupoFuncionalidades}" var="funcionalidade" class="table table-hover">
                    <h:column>
                        <f:facet name="header">Nome</f:facet>
                        <h:outputText value="#{funcionalidade.nome}"/>
                    </h:column>

                    <h:column>
                        <f:facet name="header">Remover</f:facet>
                        <h:commandLink id="btnRemove" disabled="#{!grupoController.isNotConstant(grupoFuncionalidadesController.idGrupo)}" value="Remover" action="#{grupoFuncionalidadesController.remover(funcionalidade)}" class="btn btn-danger#{grupoFuncionalidadesController.removeDisabled(grupoFuncionalidadesController.idGrupo)}"/>
                    </h:column>
                </h:dataTable>
            </div>
            </div>
            
        </h:form>
    </ui:define>
</ui:composition>

</html>

web/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
   <f:view>
      <h:outputLabel value="Hello, world"/>
   </f:view>
</html>